### ISSUE TITLE
Speedtest not executed in Container

### ISSUE THREAD

**Issue by RiRa12621** [lisa/speedtest-go-exporter#5]
Speedtests are not executed due to unknown certificates:

```
$ docker logs -f 255865793e8c
I0401 10:02:33.780411       1 metrics.go:133] Starting listener...
I0401 10:04:34.962415       1 metrics.go:78] Processing...
W0401 10:04:35.030981       1 metrics.go:82] Warning encounted while running speedtest: Get "https://www.speedtest.net/speedtest-config.php": x509: certificate signed by unknown authority. Not adding to Metrics channel
```

## Environment
```
CONTAINER ID   IMAGE                             COMMAND                  CREATED         STATUS         PORTS                                       NAMES
255865793e8c   quay.io/lisa/speedtest-exporter   "/speedtest-exporter…"   4 minutes ago   Up 4 minutes   0.0.0.0:3030->8080/tcp, :::3030->8080/tcp   speedtest-exporter
```

```
$ uname -a
Linux clouder 4.18.0-365.el8.x86_64 #1 SMP Thu Feb 10 16:11:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Using the `latest` image from quay.io/lisa/speedtest-exporter

**Comment by lisa** [comment]
Thanks Rick. I'll take a closer look.

**Comment by lisa** [comment]
This is unsurprisingly a tagging/build system problem. Subsequent builds include the TLS bundle, but latest somehow does not.

I'll build a new `latest` and see what's to do about automating the build process somehow.

**Comment by lisa** [comment]
I've tagged v2022.04.1 and have built a new `latest` from it (10deae6a3281939100c3b314e754adfa2308d206). It should be up on the registry at:

* `quay.io/lisa/speedtest-exporter:latest`
* `quay.io/lisa/speedtest-exporter:22.04.1`
